# MySQL Datasource
spring.datasource.url=jdbc:mysql://localhost:3306/db_example
spring.datasource.username=root
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update

# MongoDB Datasource
spring.data.mongodb.uri=mongodb://localhost:27017/mongodb_example

# Elasticsearch Datasource
spring.elasticsearch.uris=http://localhost:9200
