spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_example
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      uri: mongodb://localhost:27017/mongodb_example
  elasticsearch:
    uris:
      - http://localhost:9200

ai:
  vector-service:
    url: https://api.vector.ai/chat
  gemini-service:
    url: https://api.gemini.ai/chat
